swagger: '2.0'
info:
    version: '1.0.0'
    title: 'E-Commerce API'
    description: 'API for managing brands, products, and user cart'
host: 'localhost:3000'
base path: '/api'

tags: 
schemes:
    - 'http'
paths: 
    /sunglasses:
        get: 
            tags: 
            - 'store'
    /sunglasses/brands
    /sunglasses/oakley
    /sunglasses/ray-ban
    /sunglasses/levis
    /sunglasses/dkny
produces:
    - 'application/json'
